In [2]:
import pandas as pd

In [18]:
movie=pd.read_csv('data/movie.csv')
movie['是否看过']=0
movie['点赞总数']=movie.actor_1_facebook_likes+movie.actor_2_facebook_likes+movie.actor_3_facebook_likes
movie.iloc[:5,-1].head()
movie.drop('点赞总数',axis=1,inplace=True)
movie.insert(loc=0,column='差值',value=movie.gross-movie.budget)
movie.head()

,差值,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,是否看过
0,523505847.0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,...,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,0
1,9404152.0,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,...,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,0
2,-44925825.0,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,...,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,0
3,198130642.0,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,...,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,0
4,NaN,Color,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,...,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,0

In [40]:
movie.director_name
movie['director_name']
movie.loc[0:1,['director_name']]
movie.iloc[0:3,-3:-1]

   aspect_ratio  movie_facebook_likes
0          1.78                 33000
1          2.35                     0
2          2.35                 85000